# schemas/api_schema.py
from pydantic import BaseModel, Field
from typing import List, Dict, Optional

class OptimizeRequest(BaseModel):
    """Data structure required when a client submits an optimization job."""
    cv_text: str = Field(..., description="The raw parsed text or content of the user's current CV")
    job_description: str = Field(..., description="The full text target job listing description")

class JobListingResponse(BaseModel):
    """Structured formatting for active job entries found via Tavily."""
    title: str
    url: str
    snippet: str
    source: str
    # The machine-readable match tier: "strong" | "partial" | "stretch".
    # This is what clients should localize from. Optional because rows saved
    # to a user's resume history before this field existed carry only
    # match_label — see the MATCH TIER note in agents/jobs_finder.py.
    match_tier: Optional[str] = None
    # English prose form of match_tier. Kept for those older saved rows.
    match_label: str

class OptimizeResponse(BaseModel):
    """Data structure returned to the client upon successful pipeline completion."""
    success: bool
    match_score: float = Field(..., description="The overall alignment percentage calculated by Agent 5")
    cover_letter_text: str = Field(..., description="The raw prose generated by Agent 4a")
    similar_jobs: List[JobListingResponse] = Field(default=[], description="List of active parallel job leads found")
    pdf_cv_path: Optional[str] = Field(None, description="Local path or asset download link for the tailored PDF CV")
    pdf_cl_path: Optional[str] = Field(None, description="Local path or asset download link for the cover letter PDF")